# Generated by Django 2.1 on 2019-04-03 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesize', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])])),
            ],
        ),
    ]
