# Generated by Django 2.1 on 2019-04-04 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190404_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='url',
            field=models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])]),
        ),
    ]
