# Generated by Django 2.1 on 2019-04-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190404_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='text_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
